uploads = []

[[generated]]
id = "NNxYvvs4OdSzitWYJnhme"
uri = "file://artifacts/thankatech-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "Ctx5pend0okNQLd8PzS-p"
uri = "file://artifacts/thankatech/public/twitter-banner.svg"
type = "image"
title = "ThankATech Twitter Banner (1500×500)"

[[outputs]]
id = "c2n_3Cwnl5LBTf9xIfM9H"
uri = "file://artifacts/thankatech/public/profile-picture.svg"
type = "image"
title = "ThankATech Profile Picture (400×400)"
